### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by RileyAK** [PolicyEngine/child-tax-credit-expansion-impact#13]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://policyengine-trafwa-child-tax-credit.streamlit.app/policyengine/child-tax-credit-expansion-impact/main/app.py) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by MaxGhenis** [comment]
I think we're ok now that we consolidated the Simulation calls and added a Calculate button. Thanks for reporting this!
